# Generated by Django 4.2 on 2026-03-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("thumbnail", models.TextField(blank=True, null=True)),
                ("is_active", models.IntegerField(default=1)),
                ("is_featured", models.IntegerField(default=0)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("festival", "Festival"),
                            ("daily", "Daily"),
                            ("greeting", "Greeting"),
                            ("motivation", "Motivation"),
                            ("business", "Business"),
                        ],
                        default="business",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("state_id", models.IntegerField(default=0)),
                ("is_top", models.IntegerField(default=0)),
                ("image", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cities",
                "ordering": ["city"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileDailyVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                ("visits", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "profile_daily_visits",
                "ordering": ["-visit_date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_title", models.CharField(max_length=199)),
                ("description", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("thumbnail", models.TextField(blank=True, null=True)),
                ("is_active", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "services",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=199, null=True)),
                ("email", models.CharField(max_length=199)),
                ("phone", models.CharField(blank=True, max_length=199, null=True)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=199, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("state", models.IntegerField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=199, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("facebook", models.TextField(blank=True, null=True)),
                ("linkedin", models.TextField(blank=True, null=True)),
                (
                    "whatsapp_no",
                    models.CharField(blank=True, max_length=199, null=True),
                ),
                ("visiting_card_url", models.TextField(blank=True, null=True)),
                ("is_active", models.IntegerField(default=1)),
                ("is_verified", models.IntegerField(default=0)),
                ("is_email_verified", models.IntegerField(default=0)),
                ("is_profile_complete", models.IntegerField(default=0)),
                ("is_document_uploaded", models.IntegerField(default=0)),
                ("is_my_business_uploaded", models.IntegerField(default=0)),
                ("profile_percentage", models.IntegerField(default=0)),
                ("added_from", models.CharField(default="app", max_length=10)),
                ("user_from", models.CharField(default="app", max_length=10)),
                ("login_type", models.CharField(default="email", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChatApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("is_answered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chatapp",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("bot_response", models.TextField()),
                ("intent", models.CharField(default="unknown", max_length=50)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(default="english", max_length=20)),
                ("response_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
